dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T project1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb bluer-sys:25515f400eaebfb1887f5370b0e61d1b23237a85 "https://api.bintray.com/content/bluersys/CPP/project_1_bin/$TRAVIS_BUILD_NUMBER/project1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
