dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T project1-0.0.$TRAVIS_JOB_ID-Linux.deb bluer-sys:$BINTRAY_API_KEY "https://api.bintray.com/content/bluersys/CPP/project_1_bin/$TRAVIS_JOB_ID/project1-0.0.$TRAVIS_JOB_ID-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
